AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    disneyTokenService

    SAM Template for retrieving an API token to use with Disney's API.
    
Globals:
    Function:
        Timeout: 3


Resources:
    DisneyTokenServiceFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: disneyTokenService/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10

Outputs:

    DisneyTokenServiceFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt DisneyTokenServiceFunction.Arn

    DisneyTokenServiceFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt DisneyTokenServiceFunction.Arn
